name: Releases

on:
  push:

jobs:
  release:
    uses: pimalaya/nix/.github/workflows/releases.yml@master
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    with:
      project: himalaya
