name: Release

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-darwin
            os: macos-14
          - target: aarch64-linux
            os: ubuntu-latest
          - target: armv6l-linux
            os: ubuntu-latest
          - target: armv7l-linux
            os: ubuntu-latest
          - target: i686-linux
            os: ubuntu-latest
          # FIXME
          # - target: i686-windows
          #   os: ubuntu-latest
          - target: x86_64-darwin
            os: macos-13
          - target: x86_64-linux
            os: ubuntu-latest
          - target: x86_64-windows
            os: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          # TODO: until PR #358989 get merged
          # nix_path: nixpkgs=channel:nixos-unstable
          nix_path: nixpkgs=https://github.com/soywod/nixpkgs/archive/master.tar.gz
          enable_kvm: true
          extra_nix_config: experimental-features = nix-command flakes
      - name: Cache Nix store
        uses: cachix/cachix-action@v15
        with:
          name: soywod
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Build release
        run: nix build .#cross-${{ matrix.target }}
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.project }}-${{ matrix.target }}
          path: result/bin/${{ inputs.project }}*
      - name: Upload share folder
        uses: actions/upload-artifact@v4
        if: ${{ matrix.target == 'x86_64-linux' }}
        with:
          name: share
          path: result/share
      - name: Upload CHANGELOG.md
        uses: actions/upload-artifact@v4
        if: ${{ matrix.target == 'x86_64-linux' }}
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md

  release:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/')
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-darwin
          - target: aarch64-linux
          - target: armv6l-linux
          - target: armv7l-linux
          - target: i686-linux
          # FIXME
          # - target: i686-windows
          - target: x86_64-darwin
          - target: x86_64-linux
          - target: x86_64-windows
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: List
        run: ls -al
      - name: Upload releases
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files:
            ${{ inputs.project }}-${{ matrix.target }}/${{ inputs.project }}*
            share
